### ISSUE TITLE
Make use of com.solab.iso8583.parse.ConfigParser to support j8583 configs

### ISSUE THREAD

**Issue by kpavlov** [keyhan/jBSBE#3]
I think it would simplify migration to your library.

**Comment by keyhan** [comment]
Hi, you are right. I will take time for it in near future.

**Comment by keyhan** [comment]
I was thinking a bit, xml configuration is a bit of old now, the cool thing is to do yaml configuration, I think I will do that as well ;). But I have to get over time for it.

**Comment by keyhan** [comment]
@kpavlov OK, now I have implemented support for templates via yaml-file. Look at readme and read the code in I50Utility class and the SchemaImporterTest to see how it works.

For the Message configuration I do not use any configuration file. The POJO will hold the configuration by annotations. That is much simpler than having a pojo and a separate XML file for the configuration. That is the whole thing with this library. I would love a comment.
