### ISSUE TITLE
can't find builder method for PurchaseRequest

### ISSUE THREAD

**Issue by WimpyMistake** [keyhan/jBSBE#4]
I have this class similar to this:

```import java.util.Date;

import org.mashad.jbsbe.annotation.Iso8583;
import org.mashad.jbsbe.annotation.IsoField;

import lombok.Builder;

@Iso8583(type=0x200)
@Builder
public class PurchaseRequest {
	@IsoField(index=10)
	public Date date;
	@IsoField(index=4)
	public Long amount;
	@IsoField(index=11)
	public Integer stan;
	@IsoField(index=35)
	public String cardNumber;
}
```
from which taken from your UnitTest.
However, when i'm trying access the builder, like in your example,
`PurchaseRequest purchaseRequest = PurchaseRequest.builder()`
i couldn't use the .builder() method as its not available (no content assist, manual type resulted in compile error.

Tried to remove the `@Builder` like in your readme file also is not working.

**Comment by keyhan** [comment]
@Builder is lombok annotation, so you need the lombok jar. look at: https://projectlombok.org/ for how it works. Remember that you have to install its plugin on the IDE you use, it is all described in the link.
